config/routes.rb
Mathalarm::Application.routes.draw do
  
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :alarms, only: [:index, :show] do
        resources :samples, except: [:new, :edit]
      end
    end
  end

  resources :home, only: [:index]
  resources :plans, only: [:index]
  
  match "/alarms/:id/export(/:notification_id)", as: "export_alarm", to: "alarms#export", via: [:get] 
  
  resources :alarms do
    resources :samples, except: [:show]
    resources :receivers, except: [:show]
    resources :notifications, only: [:index, :show]
    resources :imports, only: [:new, :create]    
  end
  
  root :to => 'home#index'

end

app/models/receiver.rb
# encoding: utf-8
class Receiver < ActiveRecord::Base
  paginates_per 10
  
  belongs_to :alarm
  
  validates_presence_of :name, :message => "El destinatario no puede estar vacío."
  validates :name, :length => { :maximum => 255, 
                                :too_long => "El destinatario no puede tener más de %{count} caracteres."}
  
  def is_email?
    !self.name.nil? && self.name.partition("@").none?{ |x| x.blank? }
  end
  
  def is_twitter?
    !self.name.nil? && self.name.starts_with?("@") && !self.name.partition("@")[2].blank?
  end
  
end

app/controllers/receivers_controller.rb
#encoding: utf-8
class ReceiversController < ApplicationController
  before_filter :authenticate_user!
  
  decorates_assigned :receiver
  
  # GET /alarms/:alarm_id/receivers
  def index
    @alarm = current_user.alarms.find_by_id(params[:alarm_id]) || not_found
    @receivers = @alarm.receivers.order("created_at desc").page(params[:page])
    @receivers_page = params[:page].present? ? params[:page].to_i : 1  
  end

  # GET /alarms/:alarm_id/receivers/new
  def new
    @alarm = current_user.alarms.find_by_id(params[:alarm_id]) || not_found
    @receiver = Receiver.new
    @receiver.alarm_id = @alarm.id
    @url = alarm_receivers_path(@alarm, {:show => true})
  end

  # GET /alarms/:alarm_id/receivers/1/edit
  def edit
    @alarm = current_user.alarms.find_by_id(params[:alarm_id]) || not_found
    @receiver = @alarm.receivers.find_by_id(params[:id]) || not_found
    @url = alarm_receiver_path(@alarm, @receiver, { :page => params[:page] })
  end

  # POST /alarms/:alarm_id/receivers
  def create
    @from_alarm_show = params[:show].present?
    @receivers_page = params[:page].present? ? params[:page].to_i : 1
      
    @alarm = current_user.alarms.find_by_id(params[:alarm_id]) || not_found  
    begin      
      @receiver = Receiver.new(params[:receiver])    
      @alarm.receivers << @receiver
      @receivers = @alarm.receivers.order("created_at desc").page(@receivers_page)
      @message = "Se ha añadido un destinatario a la alarma <b>#{@alarm.name}</b>"
      @status = :created  
    rescue
      @message = "No se ha podido añadir un destinatario a la alarma <b>#{@alarm.name}</b>"
      @status = :unprocessable_entity
    end
    
    respond_to do |format|
      format.js
      format.html {
        if status == :created
          redirect_to @alarm, notice: @message
        else
          render action: "new"
        end
      }      
    end
  end

  # PUT /alarms/:alarm_id/receivers/1
  def update
    @receivers_page = params[:page].present? ? params[:page].to_i : 1
      
    @alarm = current_user.alarms.find_by_id(params[:alarm_id]) || not_found
    @receiver = @alarm.receivers.find_by_id(params[:id]) || not_found  
    begin      
      @receivers = @alarm.receivers.order("created_at desc").page(@receivers_page)    
      result = @receiver.update_attributes(params[:receiver])
      @message = "Se ha modificado el destinatario <b>#{@receiver.name}</b> correctamente."      
      @status = :ok
    rescue
      result = false
      @message = "¡Vaya! No se ha podido eliminar el destinatario <b>#{@receiver.name}</b>."
      @status = :unprocessable_entity
    end

    respond_to do |format|
      if result
        format.js
        format.html { redirect_to @receiver, notice: @message }
      else
        format.js
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /alarms/:alarm_id/receivers/1
  def destroy
    @receivers_page = params[:page].present? ? params[:page].to_i : 1
    
    @alarm = current_user.alarms.find_by_id(params[:alarm_id]) || not_found
    @receiver = @alarm.receivers.find_by_id(params[:id]) || not_found  
    begin
      @receiver.destroy
      @receivers = @alarm.receivers.order("created_at desc").page(@receivers_page)
      
      # Si en la página sólo había un receptor y lo hemos borrado debemos irnos a la página anterior
      if @receivers_page > 1 && @receivers.blank?
        @receivers_page -= 1        
        @receivers = @alarm.receivers.order("created_at desc").page(@receivers_page)
      end
      
      @message = "Se ha eliminado el destinatario <b>#{@receiver.name}</b> correctamente."      
      @status = :ok
    rescue
      @message = "¡Vaya! No se ha podido eliminar el destinatario <b>#{@receiver.name}</b>."       
      @status = :unprocessable_entity
    end

    respond_to do |format|
      format.js
      format.html { redirect_to alarm_receivers_url(@alarm) }
    end
  end
end

app/views/receivers/_form.html.erb
<%= form_for(@receiver, 
             :url => @url,
             :html => { :role => "form", 
                        :class => "form-inline", 
                        :remote => true}) do |f| %>
  <% if @receiver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@receiver.errors.count, "error") %> prohibited this receiver from being saved:</h2>

      <ul>
      <% @receiver.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group col-md-5 receiver">   
    <%= f.text_field :name, :class => "form-control receiver", :placeholder => "Nuevo destinatario..." %>         
  </div>
  <div class="form-group">
    <button type="submit" class="form-control btn btn-primary">Guardar</button>
  </div>
  <div class="form-group">
    <button id="cancel-<%= @receiver.new_record? ? "new" : "add" %>-receiver<%= "-#{@receiver.id}" unless @receiver.new_record? %>" type="button" class="form-control btn btn-warning">Cancelar</button>
  </div>
<% end %>

app/views/receivers/_receivers_table.html.erb
<div class="row">
  <% if alarm.has_receivers? %>
    <div class="col-md-8 alarm-tab">
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Destinatario</th>
            <th>Modo de envío</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% ReceiverDecorator.decorate_collection(receivers).each_with_index do |r, i| %>
            <tr class="receiver-row">
              <td><%= (10 * (page - 1)) + i + 1 %></td>
              <td><%= r.name %></td>
              <td><%= r.network %></td>
              <td>
                 <a id="edit-receiver-button" href="<%= edit_alarm_receiver_path(alarm, r, { :page => page }) %>" title="Editar" class="btn btn-primary btn-xs" data-remote="true">
                   <span class="glyphicon glyphicon-pencil"></span>
                 </a>
                 <button id="delete-receiver-<%= alarm.id %>" title="Eliminar" type="button" class="btn btn-primary btn-xs">
                   <span class="glyphicon glyphicon-remove"></span>
                 </a>
              </td>           
            </tr>
            <tr class="hide edit-receiver-row">
              <td colspan="4">  
                <div id="edit-receiver-placeholder-<%= r.id %>">
                </div>            
              </td>
            </tr>
            <tr class="hide delete-receiver-message">
              <td colspan="4">
                <div class="alert alert-danger">
                  ¿Realmente quieres eliminar a <b><%= r.name %></b> como destinatario?
                  <button id="cancel-delete-receiver-{{id}}" type="button" class="btn btn-primary">No</button>
                  <a href="<%= alarm_receiver_path(alarm, r, { :page => page })%>" class="btn btn-warning" data-remote="true" data-method="delete">Sí</a>
                </div>
              </td>              
            </tr>
          <% end %>    
        </tbody>
      </table>
    </div>
  <% end %>
</div>

app/views/receivers/_tab_receivers.html.erb
<div id="receivers-container">
  <%= render partial: "receivers/receivers_table", locals: { alarm: alarm, receivers: receivers, page: page } %>
</div>

<div id="receiver-paginator">
  <%= paginate receivers, :params => { :controller => "receivers", :action => "index", :alarm_id => alarm.id }, :remote => true %>
</div>

<div id="add-receiver-form" class="row add-container hide">
  <div id="add-receiver-container" class="col-md-8">   
    <div id="new-receiver-placeholder">
    </div>
  </div>
</div>

<div id="add-receiver-button-container" class="row add-container">
  <div class="col-md-3">    
    <a id="add-receiver-button" href="<%= new_alarm_receiver_path(alarm) %>" class="btn btn-primary btn-block" data-remote="true">Añadir destinatario</a>
  </div>
</div>

app/views/receivers/create.js.erb
$.pnotify({
  text: '<%= @message.html_safe %>',
  type: '<%= @status == :created ? "success" : "error" %>'
});

<% if @status == :created %>  
  <% unless @from_alarm_show %>        
    $("#alarm-<%= @alarm.id %>").replaceWith($(Mustache.to_html($('#alarm_template').html(), <%= AlarmDecorator.decorate(Alarm.find(@alarm.id)).to_json.html_safe %>)));
    bind_manage_form_controls();   
  <% else %>
    hide_add_receiver_form();
    $("#receivers-container").html('<%= escape_javascript(render(partial: "receivers_table", 
                                                                 locals: { alarm: AlarmDecorator.decorate(@alarm), 
                                                                           receivers: @receivers,
                                                                           page: @receivers_page }).html_safe) %>');
    $("#receiver-paginator").html('<%= escape_javascript(paginate(@receivers, :params => { :controller => "receivers", :action => "index", :alarm_id => @alarm.id }, :remote => true).to_s) %>');                                                                           
    bind_receivers_buttons();    
    $("#no-receivers-main-message").addClass("hide"); 
    $("#tab-receivers-link").html('<%= AlarmDecorator.decorate(@alarm).tab_receivers_title %>')   
  <% end %>
<% end %>

app/views/receivers/destroy.js.erb
$.pnotify({
  text: '<%= @message.html_safe %>',
  type: '<%= @status == :ok ? "success" : "error" %>'
});

<% if @status == :ok %>  
  $("#receivers-container").html('<%= escape_javascript(render(partial: "receivers_table", 
                                                               locals: { alarm: AlarmDecorator.decorate(@alarm), 
                                                                         receivers: @receivers,
                                                                         page: @receivers_page }).html_safe) %>');
  $("#receiver-paginator").html('<%= escape_javascript(paginate(@receivers, :params => { :controller => "receivers", :action => "index", :alarm_id => @alarm.id }, :remote => true).to_s) %>');                                                                         
  bind_receivers_buttons();   
  $("#tab-receivers-link").html('<%= AlarmDecorator.decorate(@alarm).tab_receivers_title %>')
  
  <% unless @alarm.has_receivers? %>
    $("#add-receiver-button").click();
  <% end %> 
<% end %>

app/views/receivers/edit.html.erb
<%= render "form" %>

app/views/receivers/edit.js.erb
restore_visibilities();
$("#edit-receiver-placeholder-<%= @receiver.id %>").html('<%= escape_javascript(render("form").html_safe) %>');
$("#edit-receiver-placeholder-<%= @receiver.id %>").parents("tr").removeClass("hide");
$("#edit-receiver-placeholder-<%= @receiver.id %>").parents("tr").prev("tr").addClass("hide");
$("#cancel-add-receiver-<%= @receiver.id %>").on("click", function(){
  restore_visibilities();
});

app/views/receivers/index.js.erb
restore_visibilities();
$("#receivers-container").html('<%= escape_javascript(render(partial: "receivers_table", 
                                                             locals: { alarm: AlarmDecorator.decorate(@alarm), 
                                                                       receivers: @receivers,
                                                                       page: @receivers_page }).html_safe) %>');
$("#receiver-paginator").html('<%= escape_javascript(paginate(@receivers, :params => { :controller => "receivers", :action => "index", :alarm_id => @alarm.id }, :remote => true).to_s) %>');
bind_receivers_buttons(); 

app/views/receivers/new.html.erb
<div class="row">
  <%= render "form" %>
</div>

app/views/receivers/new.js.erb
restore_visibilities();
$("#add-receiver-button-container").addClass("hide");
$("#new-receiver-placeholder").html('<%= escape_javascript(render("form").html_safe) %>');
$("#add-receiver-form").removeClass("hide")
$("#cancel-new-receiver").on("click", function(){
  hide_add_receiver_form();
});

app/views/receivers/update.js.erb
$.pnotify({
  text: '<%= @message.html_safe %>',
  type: '<%= @status == :ok ? "success" : "error" %>'
});

<% if @status == :ok %> 
  $("#receivers-container").html('<%= escape_javascript(render(partial: "receivers_table", 
                                                               locals: { alarm: AlarmDecorator.decorate(@alarm), 
                                                                         receivers: @receivers,
                                                                         page: @receivers_page }).html_safe) %>');
  $("#receiver-paginator").html('<%= escape_javascript(paginate(@receivers, :params => { :controller => "receivers", :action => "index", :alarm_id => @alarm.id }, :remote => true).to_s) %>');
  bind_receivers_buttons();    
<% end %>