config/routes.rb
Mathalarm::Application.routes.draw do
  
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :alarms, only: [:index, :show] do
        resources :samples, except: [:new, :edit]
      end
    end
  end

  resources :home, only: [:index]
  resources :plans, only: [:index]
  
  match "/alarms/:id/export(/:notification_id)", as: "export_alarm", to: "alarms#export", via: [:get] 
  
  resources :alarms do
    resources :samples, except: [:show]
    resources :receivers, except: [:show]
    resources :notifications, only: [:index, :show]
    resources :imports, only: [:new, :create]    
  end
  
  root :to => 'home#index'

end

app/models/sample.rb
# encoding: utf-8
class Sample < ActiveRecord::Base
  paginates_per 10
  
  belongs_to :alarm
  
  attr_accessor :has_triggered_alarm, :is_imported
  
  validates_numericality_of :value, :message => "El valor de la muestra debe ser numérico"
  
  after_create :increase_alarm_samples_counter, :check_alarm
  after_destroy :decrease_alarm_samples_counter
  
  def increase_alarm_samples_counter
    current_alarm = self.alarm
    current_alarm.update_attributes(:samples_count => current_alarm.samples_count + 1)     
  end
  
  def decrease_alarm_samples_counter
    current_alarm = self.alarm
    current_alarm.update_attributes(:samples_count => current_alarm.samples_count - 1)     
  end
  
  def check_alarm
    unless self.is_imported
      current_alarm = self.alarm
      if current_alarm.check
        # Registramos la notificación
        current_alarm.notifications << Notification.new({ :sample_id => self.id })
        # Y marcamos la muestra como desencadenante de una alarma
        self.has_triggered_alarm = true
      end
    end
  end
  
end

app/controllers/api/v1/samples_controller.rb
#encoding: utf-8
module Api
  module V1
    
    class SamplesController < ApplicationController
      respond_to :json
      
      before_filter :api_authenticate
          
      # GET /api/v1/alarms/:alarm_id/samples.json
      def index
        alarm = @api_user.alarms.find_by_id(params[:id])
        samples = alarm.nil? ? [] : alarm.samples.order("created_at desc, id desc").page(params[:page])
        render :json => SampleDecorator.decorate_collection(samples).as_json( :from_api => true ), status: :ok
      end
      
      # GET /api/v1/alarms/:alarm_id/samples/1.json
      def show
        alarm = @api_user.alarms.find_by_id(params[:id])
        sample = alarm.nil? ? nil : alarm.samples.find_by_id(params[:id])
        if sample.nil? || alarm.nil?
          render :json => {}.as_json, status: :unauthorized
        else
          render :json => SampleDecorator.decorate(sample).as_json( :from_api => true ), status: :ok
        end
      end

      # POST /api/v1/alarms/:alarm_id/samples.json
      def create               
        begin
          alarm = @api_user.alarms.find_by_id(params[:id])
          if alarm.nil?
            result = "No se ha podido añadir una muestra a la alarma."
            status = :unauthorized
          else
            sample = Sample.new(params[:sample])     
            alarm.samples << sample
            status = :created          
            result = SampleDecorator.decorate(sample).as_json( :from_api => true )
          end          
        rescue
          result = "No se ha podido añadir una muestra a la alarma."
          status = :unprocessable_entity
        end
        
        render :json => result, status: status        
      end
      
      # PUT /api/v1/alarms/:alarm_id/samples/1.json
      def update                 
        begin
          alarm = @api_user.alarms.find_by_id(params[:id])
          sample = alarm.nil? ? nil : alarm.samples.find_by_id(params[:id]) 
          if sample.nil? || alarm.nil? 
            result = "No se ha podido añadir una muestra a la alarma."
            status = :unauthorized 
          else
            sample.update_attributes(params[:sample])         
            status = :created
            result = SampleDecorator.decorate(sample).as_json( :from_api => true )            
          end
        rescue
          result = "No se ha podido añadir una muestra a la alarma."
          status = :unprocessable_entity
        end
                
        render :json => result, status: status       
      end
      
      # DELETE /api/v1/alarms/:alarm_id/samples/1
      def destroy
        result = nil  
        begin
          alarm = @api_user.alarms.find_by_id(params[:id])
          sample = alarm.nil? ? nil : alarm.samples.find_by_id(params[:id])
          if sample.nil? || alarm.nil?    
            result = "No se ha podido añadir una muestra a la alarma."
            status = :unauthorized
          else
            sample.destroy         
            status = :ok
            result = SampleDecorator.decorate(sample).as_json( :from_api => true )            
          end
        rescue
          result = "No se ha podido añadir una muestra a la alarma."
          status = :unprocessable_entity
        end
        
        render :json => result, status: status
      end
      
    end
  end
end

app/controllers/samples_controller.rb
#encoding: utf-8
class SamplesController < ApplicationController
  before_filter :authenticate_user!
  
  decorates_assigned :sample
  
  # GET /alarms/:alarm_id/samples
  def index
    @alarm = current_user.alarms.find_by_id(params[:alarm_id]) || not_found
    @samples = @alarm.samples.order("created_at desc, id desc").page(params[:page])
    @samples_page = params[:page].present? ? params[:page].to_i : 1
  end

  # GET /alarms/:alarm_id/samples/new
  def new
    @alarm = current_user.alarms.find_by_id(params[:alarm_id]) || not_found
    @sample = Sample.new
    @sample.alarm_id = @alarm.id
    @url = alarm_samples_path(@alarm, {:show => true})
  end

  # GET /alarms/:alarm_id/samples/1/edit
  def edit
    @alarm = current_user.alarms.find_by_id(params[:alarm_id]) || not_found
    @sample = @alarm.samples.find_by_id(params[:id]) || not_found
    @url = alarm_sample_path(@alarm, @sample, { :page => params[:page] })
  end

  # POST /alarms/:alarm_id/samples
  def create
    @from_alarm_show = params[:show].present?
    @samples_page = params[:page].present? ? params[:page].to_i : 1
    
    @alarm = current_user.alarms.find_by_id(params[:alarm_id]) || not_found    
    begin
      @sample = Sample.new(params[:sample])     
      @alarm.samples << @sample
      if @sample.errors.blank?        
        @alarm = Alarm.find(params[:alarm_id])      
        if @sample.has_triggered_alarm
          @notifications = @alarm.notifications.order("created_at desc, id desc").page(1)
          @notifications_page = 1
        end
        @samples = @alarm.samples.order("created_at desc, id desc").page(@samples_page)
        @message = "Se ha añadido una muestra a la alarma <b>#{@alarm.name}</b>"
        @status = :created
      else
        @message = "#{@sample.errors.first[1]}.<br><br>No se ha podido añadir una muestra a la alarma <b>#{@alarm.name}</b>"
        @status = :unprocessable_entity
      end
    rescue
      @message = "No se ha podido añadir una muestra a la alarma <b>#{@alarm.name}</b>"
      @status = :unprocessable_entity
    end
    
    respond_to do |format|
      format.js
      format.html {
        if @status == :created
          redirect_to @alarm, notice: @message
        else
          render action: "new"
        end
      } 
    end
  end

  # PUT /alarms/:alarm_id/samples/1
  def update
    @samples_page = params[:page].present? ? params[:page].to_i : 1
     
    @alarm = current_user.alarms.find_by_id(params[:alarm_id]) || not_found  
    @sample = @alarm.samples.find_by_id(params[:id]) || not_found 
    begin      
      result = @sample.update_attributes(params[:sample])
      @samples = @alarm.samples.order("created_at desc, id desc").page(@samples_page)      
      @message = "Se ha modificado la muestra <b>#{sample.value}</b> creada el <b>#{sample.created_at}</b> correctamente."      
      @status = :ok
    rescue
      result = false
      @message = "¡Vaya! No se ha podido eliminar la muestra <b>#{@sample.name}</b> creada el <b>#{sample.created_at}</b>."
      @status = :unprocessable_entity
    end

    respond_to do |format|
      if result
        format.js
        format.html { redirect_to @sample, notice: @message }
      else
        format.js
        format.html { render action: "edit" }        
      end
    end
  end

  # DELETE /alarms/:alarm_id/samples/1
  def destroy
    @samples_page = params[:page].present? ? params[:page].to_i : 1
    
    @alarm = current_user.alarms.find_by_id(params[:alarm_id]) || not_found  
    @sample = @alarm.samples.find_by_id(params[:id]) || not_found 
    begin
      @sample.destroy      
      @alarm = Alarm.find(params[:alarm_id])
      @samples = @alarm.samples.order("created_at desc, id desc").page(@samples_page)
      
      # Si en la página sólo había una muestra y la hemos borrado debemos irnos a la página anterior
      if @samples_page > 1 && @samples.blank?
        @samples_page -= 1        
        @samples = @alarm.samples.order("created_at desc, id desc").page(@samples_page)
      end
      
      @message = "Se ha eliminado la muestra <b>#{sample.value}</b> creada el <b>#{sample.created_at}</b> correctamente."      
      @status = :ok
    rescue
      @message = "¡Vaya! No se ha podido eliminar la muestra <b>#{sample.value}</b> creada el <b>#{sample.created_at}</b>."       
      @status = :unprocessable_entity
    end

    respond_to do |format|
      format.js
      format.html { redirect_to alarm_samples_url(@alarm) }
    end       
  end  

end

app/views/samples/_form.html.erb
<%= form_for(@sample, 
             :url => @url,
             :html => { :role => "form", 
                        :class => "form-inline", 
                        :remote => true}) do |f| %>
  <% if @sample.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sample.errors.count, "error") %> prohibited this sample from being saved:</h2>

      <ul>
      <% @sample.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group col-md-5 sample">   
    <%= f.text_field :value, :class => "form-control sample", :placeholder => "Nueva muestra..." %>         
  </div>
  <div class="form-group">
    <button type="submit" class="form-control btn btn-primary">Guardar</button>
  </div>
  <div class="form-group">
    <button id="cancel-<%= @sample.new_record? ? "new" : "add" %>-sample<%= "-#{@sample.id}" unless @sample.new_record? %>" type="button" class="form-control btn btn-warning">Cancelar</button>
  </div>
<% end %>

app/views/samples/_samples_table.html.erb
<div class="row">
  <% if alarm.has_samples? %>
    <div class="col-md-8 alarm-tab">
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Fecha</th>
            <th>Muestra</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% SampleDecorator.decorate_collection(samples).each_with_index do |s, i| %>
            <tr class="sample-row">
              <td><%= (10 * (page - 1)) + i + 1 %></td>
              <td><%= s.created_at %></td>
              <td><%= s.value %></td>
              <td>
                 <a id="edit-sample-button" href="<%= edit_alarm_sample_path(alarm, s, { :page => page }) %>" title="Editar" class="btn btn-primary btn-xs" data-remote="true">
                   <span class="glyphicon glyphicon-pencil"></span>
                 </a>
                 <button id="delete-sample-<%= alarm.id %>" type="button" class="btn btn-primary btn-xs" title="Eliminar">
                   <span class="glyphicon glyphicon-remove"></span>
                 </a>
              </td>           
            </tr>
            <tr class="hide edit-sample-row">
              <td colspan="4">  
                <div id="edit-sample-placeholder-<%= s.id %>">
                </div>            
              </td>
            </tr>
            <tr class="hide delete-sample-message">
              <td colspan="4">
                <div class="alert alert-danger">
                  ¿Realmente quieres eliminar la muestra <b><%= s.value %></b> creada el <%= s.created_at %>
                  <button id="cancel-delete-sample-{{id}}" type="button" class="btn btn-primary">No</button>
                  <a href="<%= alarm_sample_path(alarm, s, { :page => page })%>" class="btn btn-warning" data-remote="true" data-method="delete">Sí</a>
                </div>
              </td>              
            </tr>
          <% end %>    
        </tbody>
      </table>
    </div>
  <% end %>
</div>

app/views/samples/_tab_samples.html.erb
<div id="samples-container">
  <%= render partial: "samples/samples_table", locals: { alarm: alarm, samples: samples, page: page } %>
</div>

<div id="sample-paginator">
  <%= paginate samples, :params => { :controller => "samples", :action => "index", :alarm_id => alarm.id }, :remote => true %>
</div>

<div id="add-sample-form" class="row add-container hide">
  <div id="add-sample-container" class="col-md-8">   
    <div id="new-sample-placeholder">
    </div>
  </div>
</div>

<div id="add-sample-button-container" class="row add-container">
  <div class="col-md-3">    
    <a id="add-sample-button" href="<%= new_alarm_sample_path(alarm) %>" class="btn btn-primary btn-block" data-remote="true">Añadir muestra</a>
  </div>
  <div class="col-md-3">
    <a id="import-sample-button" href="#" class="btn btn-primary btn-block">Importar</a>
  </div>
  <div class="col-md-3">
    <a id="export-sample-button" href="<%= export_alarm_path(alarm) %>" class="btn btn-primary btn-block">Exportar</a>
  </div>
</div>

<%= render :partial => "/imports/dialog", :locals => { :alarm => @alarm } %>

app/views/samples/create.js.erb
$.pnotify({
  text: '<%= @message.html_safe %>',
  type: '<%= @status == :created ? "success" : "error" %>'
});

<% if @status == :created %>

  <% if @sample.has_triggered_alarm %>
    $.pnotify({
      text: 'Se ha cumplido la condición de la alarma',
      type: 'success'
    });  
  <% end %>
  
  <% unless @from_alarm_show %>        
    $("#alarm-<%= @alarm.id %>").replaceWith($(Mustache.to_html($('#alarm_template').html(), <%= AlarmDecorator.decorate(Alarm.find(@alarm.id)).to_json.html_safe %>)));
    bind_manage_form_controls();   
  <% else %>
    hide_add_sample_form();
    $("#samples-container").html('<%= escape_javascript(render(partial: "samples_table", 
                                                               locals: { alarm: AlarmDecorator.decorate(Alarm.find(@alarm)),
                                                                         samples: @samples,
                                                                         page: @samples_page }).html_safe) %>');
    $("#sample-paginator").html('<%= escape_javascript(paginate(@samples, :params => { :controller => "samples", :action => "index", :alarm_id => @alarm.id }, :remote => true).to_s) %>');                                                                         
    bind_samples_buttons();  
    $("#tab-samples-link").html('<%= AlarmDecorator.decorate(@alarm).tab_samples_title %>')
    <% if @sample.has_triggered_alarm %>
      $("#notifications-container").html('<%= escape_javascript(render(partial: "notifications/notifications_table", 
                                                                locals: { alarm: AlarmDecorator.decorate(@alarm), 
                                                                          notifications: @notifications,
                                                                          page: @notifications_page }).html_safe) %>');

      $("#tab-notifications-link").html('<%= AlarmDecorator.decorate(@alarm).tab_notifications_title %>')
    <% end %>  
  <% end %>
<% end %>

app/views/samples/destroy.js.erb
$.pnotify({
  text: '<%= @message.html_safe %>',
  type: '<%= @status == :ok ? "success" : "error" %>'
});

<% if @status == :ok %>  
  $("#samples-container").html('<%= escape_javascript(render(partial: "samples_table", 
                                                             locals: { alarm: AlarmDecorator.decorate(@alarm),
                                                                       samples: @samples,
                                                                       page: @samples_page }).html_safe) %>');
  $("#sample-paginator").html('<%= escape_javascript(paginate(@samples, :params => { :controller => "samples", :action => "index", :alarm_id => @alarm.id }, :remote => true).to_s) %>');                                                                       
  bind_samples_buttons();  
  $("#tab-samples-link").html('<%= AlarmDecorator.decorate(@alarm).tab_samples_title %>');
  
  <% unless @alarm.has_samples? %>
    $("#add-sample-button").click();
  <% end %> 
  
<% end %>

app/views/samples/edit.html.erb
<%= render "form" %>

app/views/samples/edit.js.erb
restore_visibilities();
$("#edit-sample-placeholder-<%= @sample.id %>").html('<%= escape_javascript(render("form").html_safe) %>');
$("#edit-sample-placeholder-<%= @sample.id %>").parents("tr").removeClass("hide");
$("#edit-sample-placeholder-<%= @sample.id %>").parents("tr").prev("tr").addClass("hide");
$("#cancel-add-sample-<%= @sample.id %>").on("click", function(){
  restore_visibilities();
});

app/views/samples/index.js.erb
restore_visibilities();
$("#samples-container").html('<%= escape_javascript(render(partial: "samples_table", 
                                                           locals: { alarm: AlarmDecorator.decorate(@alarm), 
                                                                     samples: @samples,
                                                                     page: @samples_page }).html_safe) %>');
$("#sample-paginator").html('<%= escape_javascript(paginate(@samples, :params => { :controller => "samples", :action => "index", :alarm_id => @alarm.id }, :remote => true).to_s) %>');
bind_samples_buttons(); 

app/views/samples/new.html.erb
<div class="row">
  <%= render "form" %>
</div>

app/views/samples/new.js.erb
restore_visibilities();
$("#add-sample-button-container").addClass("hide");
$("#new-sample-placeholder").html('<%= escape_javascript(render("form").html_safe) %>');
$("#add-sample-form").removeClass("hide")
$("#cancel-new-sample").on("click", function(){
  hide_add_sample_form();
});

app/views/samples/update.js.erb
$.pnotify({
  text: '<%= @message.html_safe %>',
  type: '<%= @status == :ok ? "success" : "error" %>'
});

<% if @status == :ok %> 
  $("#samples-container").html('<%= escape_javascript(render(partial: "samples_table", 
                                                             locals: { alarm: AlarmDecorator.decorate(@alarm),
                                                                       samples: @samples,
                                                                       page: @samples_page }).html_safe) %>');
  $("#sample-paginator").html('<%= escape_javascript(paginate(@samples, :params => { :controller => "samples", :action => "index", :alarm_id => @alarm.id }, :remote => true).to_s) %>');                                                                      
  bind_samples_buttons();    
<% end %>