config/routes.rb
Mathalarm::Application.routes.draw do
  
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :alarms, only: [:index, :show] do
        resources :samples, except: [:new, :edit]
      end
    end
  end

  resources :home, only: [:index]
  resources :plans, only: [:index]
  
  match "/alarms/:id/export(/:notification_id)", as: "export_alarm", to: "alarms#export", via: [:get] 
  
  resources :alarms do
    resources :samples, except: [:show]
    resources :receivers, except: [:show]
    resources :notifications, only: [:index, :show]
    resources :imports, only: [:new, :create]    
  end
  
  root :to => 'home#index'

end

app/models/alarm.rb
# encoding: utf-8
class Alarm < ActiveRecord::Base
  paginates_per 3
  
  has_many :notifications, :dependent => :destroy
  has_many :receivers, :dependent => :destroy
  has_many :samples, :dependent => :destroy
  has_many :operations, :dependent => :destroy
  belongs_to :user
  
  validates_presence_of :name, :message => "La alarma debe tener un nombre."
  validates :name, :length => { :maximum => 250, 
                                :too_long => "El nombre no puede tener más de %{count} caracteres."}
  validates :description, :length => { :maximum => 600, :too_long => "La descripción no puede tener más de %{count} caracteres." }
  
  attr_accessor :index_page
  
  before_save :parse_condition
  
  def last_notification
    self.has_notifications? ? self.notifications.order("created_at desc, id desc").first : nil
  end
  
  def ordered_notifications
    self.has_notifications? ? self.notifications.order("created_at desc, id desc") : []
  end 
  
  def ordered_samples
    self.has_samples? ? self.samples.order("created_at desc, id desc") : []
  end 
    
  def has_receivers?
    self.receivers.count > 0
  end
  
  def has_samples?
    self.samples_count > 0
  end
    
  def has_more_receivers?
    self.receivers.count > 1
  end
  
  def more_receivers_count
    self.receivers.count - 1       
  end
  
  def check
    result = []
    self.operations.eager_load(:operator).order(:position).each do |o|
      result = o.calculate(result)      
    end
    !result.blank? && result.first
  end
  
  def parse_condition
    begin
      # En primer lugar comprobamos si ha cambiado la condición
      # Si no ha cambiado no hacemos nada
      current_alarm = Alarm.find(self.id)
      if current_alarm.condition != self.condition
        optree = Parser.parse(self.condition)
        # La condición ha cambiado y es válida.
        # Borramos el árbol de operaciones actual y grabamos el nuevo
        self.operations.clear
        optree.flatten!        
        # Tenemos que completar aquellas operaciones que corresponden a la muestra con el id de la misma.
        # y la posición de cada operación
        sample_op = Operator.find_by_name("sample")
        optree.each_with_index do |x, i|
          x.first_operand = self.id if x.operator_id == sample_op.id
          x.position = i + 1
        end
        self.operations << optree
      end
    rescue
    end
  end
  
end

app/controllers/alarms_controller.rb
# encoding: utf-8
class AlarmsController < ApplicationController
  before_filter :authenticate_user!
  
  decorates_assigned :alarm

  # GET /alarms
  def index
    if params[:search].present?      
      @alarms = current_user.alarms.where("name like '%#{params[:search]}%' or description like '%#{params[:search]}%'").
                      order("has_notifications desc, created_at desc").
                      page(params[:page])
    else
      @alarms = current_user.alarms.order("has_notifications desc, created_at desc").
                      page(params[:page])
    end

    @alarms.each{ |a| a.index_page = params[:page] }

    gon.message = flash[:notice].present? ? flash[:notice].html_safe : ""
  end

  # GET /alarms/1
  def show
    @alarm = current_user.alarms.find_by_id(params[:id]) || not_found
    
    @receivers = @alarm.receivers.order("created_at desc").page(params[:page])
    @samples = @alarm.samples.order("created_at desc, id desc").page(params[:page])
    @notifications = @alarm.notifications.order("created_at desc, id desc").page(params[:page])
    
    # Clasificamos los operadores por tipo de operación
    @operator_types = OperatorType.order(:id).all
    @operators = {}
    @operator_types.each do |ot|
      @operators[ot.id] = ot.operators.order(:symbol)
    end
    
    @receivers_page = 1
    @samples_page = 1
    @notifications_page = 1
    
    gon.alarm_id = @alarm.id
    gon.samples = @samples.count 
    gon.receivers = @receivers.count
  end

  # GET /alarms/new
  def new
    @alarm = Alarm.new
    @alarm.user_id = current_user.id
  end

  # GET /alarms/1/edit
  def edit
    @alarm = current_user.alarms.find_by_id(params[:id]) || not_found
  end

  # POST /alarms
  def create
    @alarm = Alarm.new(params[:alarm])
    @alarm.user_id = current_user.id
    
    respond_to do |format|
      if @alarm.save
        format.html { redirect_to alarm_path(@alarm), notice: "Se ha creado la nueva alarma <b>#{@alarm.name}</b>".html_safe }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /alarms/1
  def update
    @alarm = current_user.alarms.find_by_id(params[:id]) || not_found
    begin      
      result = @alarm.update_attributes(params[:alarm])         
      @message = "Se ha modificado la alarma correctamente."      
      @status = :ok               
    rescue
      result = false     
    end 
        
    unless result && @alarm.errors.blank?
      result = false
      @message = "¡Vaya! No se ha podido modificar la alarma. #{@alarm.errors.first[1] unless @alarm.nil? || @alarm.errors.blank?}"
      @status = :unprocessable_entity   
    end     

    respond_to do |format|
      if result
        format.js
        format.html { redirect_to @alarm, notice: @message }
      else
        format.js
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /alarms/1
  def destroy
    @alarms_page = params[:page].present? ? params[:page].to_i : 1
    @alarm = current_user.alarms.find_by_id(params[:id]) || not_found
    begin
      @alarm.destroy
      @message = "Se ha eliminado la alarma <b>#{@alarm.name}</b> correctamente."      
      @status = :ok
    rescue
      @message = "¡Vaya! No se ha podido eliminar la alarma <b>#{@alarm.name unless @alarm.nil?}</b>."       
      @status = :unprocessable_entity
    end
    
    @alarms = Alarm.order("has_notifications desc, created_at desc").page(@alarms_page)
      
    # Si en la página sólo había una muestra y la hemos borrado debemos irnos a la página anterior
    if @alarms_page > 1 && @alarms.blank?
      @alarms_page -= 1        
      @alarms = Alarm.order("has_notifications desc, created_at desc").page(@alarms_page)
    end
    
    @alarms.each{ |a| a.index_page = @alarms_page }

    respond_to do |format|
      format.js
      format.html { redirect_to alarms_url }
    end
  end
  
  # GET /alarms/1/export
  def export
    @alarm = current_user.alarms.find_by_id(params[:id]) || not_found       
    
    if params[:notification_id].present? 
      notification = Notification.find_by_id(params[:notification_id].to_i) || not_found
      samples = @alarm.samples.where("id < ?", notification.sample_id).order(:created_at)
      date = notification.created_at.strftime("%d-%m-%Y")
    else
      samples = @alarm.samples.order(:created_at)
      date = Date.today.strftime("%d-%m-%Y")
    end
    
    file_path = "#{Rails.root}/tmp/downloads/#{@alarm.name.parameterize}-#{date}.csv"   
         
    begin       
      File.open(file_path, "w") do |f|        
        samples.each do |s|
          f.write("#{s.created_at.strftime("%d/%m/%Y %H:%M:%S")}\t#{s.value.to_s}\n")
        end
      end 
      
      send_file file_path, :type=>'text/csv' and return
    rescue
      not_found
    end 
  end
  
end

app/controllers/api/v1/alarms_controller.rb
module Api
  module V1
    class AlarmsController < ApplicationController
      respond_to :json
      
      before_filter :api_authenticate
      
      # GET /api/v1/alarms.json     
      def index
        alarms = @api_user.alarms.order("has_notifications desc, created_at desc").page(params[:page])
        respond_with AlarmDecorator.decorate_collection(alarms).as_json( :from_api => true ), status: :ok 
      end
      
      # GET /api/v1/alarms/:id.json
      def show
        alarm = @api_user.alarms.find_by_id(params[:id])
        if alarm.nil?
          render :json => {}.as_json, status: :unauthorized
        else
          render :json => AlarmDecorator.decorate(alarm).as_json( :from_api => true ), status: :ok
        end
      end
      
    end
  end
end

app/views/alarms/_alarm_info.html.erb
<div class="col-md-12">
  <h1 class="title"><%= alarm.name %></h1>
</div>
<div class="col-md-12">
  <p class="list-group-item-text text-muted">
    Creada el <%= alarm.created_at %>
  </p>
</div>
<div class="col-md-12 <%= "hide" if alarm.description.blank? %>">
  <p class="list-group-item-text alarm-description">
    <%= alarm.description %>
  </p> 
</div>

app/views/alarms/_build_alarms_timeline.js.erb
$("#alarms").html("");
<% alarms.each do |d| %>
  $("#alarms").append($(Mustache.to_html($('#alarm_template').html(), <%= AlarmDecorator.decorate(d).to_json.to_s.html_safe %>)));
<% end %>
$('#paginator').html('<%= escape_javascript(paginate(alarms, :params => { :controller => "alarms", :action => "index" }, :remote => true).to_s) %>');  
bind_manage_form_controls();  

app/views/alarms/_edit.html.erb
<div class="container">
  <div class="row">
    <div class="row index-header">
      <div class="col-md-5">
        <h1 class="title">Editando alarma</h1>
      </div>      
    </div>
    <hr>
  </div>
  <div class="row">
    <%= render "form" %>
  </div>
</div>

app/views/alarms/_form.html.erb
<%= javascript_include_tag "alarms/form" %>

<%= form_for(@alarm, :html => { :role => "form"}, :remote => !@alarm.new_record? ) do |f| %>
  <div id="form-group-name" class="form-group <%= h has_error_class(@alarm.errors, :name) %>">
    <%= f.text_field :name, :class => "form-control input-lg", :maxlength => 250, :placeholder => "Nombre de la alarma (obligatorio)" %>
    <%= render :partial => "shared/control_error_text", :locals => { :errors => @alarm.errors, :symbol => :name } %>
  </div>
  <div id="form-group-description" class="form-group <%= h has_error_class(@alarm.errors, :name) %>">
    <%= f.text_area :description, :size => "60x6", :maxlength => 600, :class => "form-control input-lg", :placeholder => "Descripción de la alarma" %>
    <%= render :partial => "shared/control_error_text", :locals => { :errors => @alarm.errors, :symbol => :description } %>
  </div>
  <div class="form-group">
    <button type="submit" class="btn btn-primary btn-lg">Guardar</button>
    <% if @alarm.new_record? %>
      <a class="btn btn-warning btn-lg" href="<%= alarms_path %>">Cancelar</a>
    <% else %>
      <button id="cancel-edit-alarm" type="button" class="btn btn-warning btn-lg">Cancelar</button>
    <% end %>
  </div>
<% end %>

app/views/alarms/_index_header.html.erb
<div class="row index-header">
  <div class="col-md-5">
    <h1 class="title">Alarmas</h1>
  </div>
  <div class="col-md-3">    
    <a class="btn btn-primary btn-lg btn-block" href="<%= new_alarm_path %>">Nueva alarma</a>       
  </div>
  <div class="col-md-4">
    <%= form_tag(alarms_path, method: "get", :id => "search-form") do %>
      <div class="input-group input-group-lg">
        <input id="search" name="search" type="text" class="form-control input" placeholder="Escribe tu búsqueda..." value="<%= params[:search] %>">
        <span class="input-group-btn">
          <button id="search-button" class="btn btn-primary" type="submit">Buscar</button>
        </span>
      </div>
    <% end %> 
  </div>    
</div>



    

app/views/alarms/_show_header.html.erb
<div id="edit-alarm-placeholder" class="col-md-12 hide">
</div>
<div class="alarm-info col-md-12 well">
  <div id="alarm-info-container">
    <%= render "alarm_info", locals: {alarm: alarm} %>  
  </div>


  <div class="col-md-10 buttons-bar">    
    <div class="btn-group">
      <a href="<%= edit_alarm_path(alarm) %>" class="btn btn-primary btn-xs" data-remote="true">Editar</a>
    </div> 
    <!--           
    <div class="btn-group">
      <button type="button" class="btn btn-primary btn-xs dropdown-toggle" data-toggle="dropdown">
        Compartir <span class="caret"></span>
      </button>
      <ul class="dropdown-menu text-left" role="menu">
        <li><a href="#">Correo electrónico</a></li>
        <li><a href="#">Facebook</a></li>
        <li><a href="#">Twitter</a></li>
      </ul>
    </div> 
    -->  
    <div class="btn-group">
      <button type="button" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#delete-sample-modal">Eliminar</button>
    </div>          
  </div>   
  <div class="col-md-2 text-right buttons-bar">
    <div class="btn-group">
      <button type="button" class="btn btn-primary btn-xs">
        <a href="<%= alarms_path %>">Volver al índice de alarmas</a>
      </button>
    </div> 
  </div> 

</div>

app/views/alarms/destroy.js.erb
$.pnotify({
  text: '<%= @message.html_safe %>',
  type: '<%= @status == :ok ? "success" : "error" %>'
}); 

<% if @status == :ok %>
  <%= render partial: "build_alarms_timeline", :locals => { :alarms => @alarms } %>
<% end %>

app/views/alarms/edit.js.erb
$("#edit-alarm-placeholder").html('<%= escape_javascript(render("edit").html_safe) %>').removeClass("hide");
$(".alarm-info").addClass("hide");
$("#cancel-edit-alarm").on("click", function(){
  $("#edit-alarm-placeholder").html('').addClass("hide");
  $(".alarm-info").removeClass("hide"); 
});

app/views/alarms/index.html.erb
<%= javascript_include_tag "alarms/import" %>

<%= render "index_header" %>

<% unless @alarms.blank? %>
  <div id="alarms" class="index">
    <% AlarmDecorator.decorate_collection(@alarms).each do |a| %>
      <%= render "alarm", :mustache => a %>
    <% end %> 
  </div>
  <div id="paginator">
    <%= paginate @alarms, :remote => true %>
  </div>       
<% else %>
  <div class="alert alert-danger">
    No se han encontrado alarmas. Pruebe con otra búsqueda.
  </div>   
<% end %> 

<%= render :partial => "/imports/dialog", :locals => { :alarm => nil } %>

<script type="text/html" id="alarm_template">
  <%= render "alarm" %>
</script>

<% content_for :script do %>
  <%= javascript_include_tag "alarms/index" %>
<% end %>

app/views/alarms/index.js.erb
<%= render partial: "build_alarms_timeline", :locals => { :alarms => @alarms } %>  
 

app/views/alarms/new.html.erb
<div class="row">
  <div class="row index-header">
    <div class="col-md-5">
      <h1 class="title">Nueva alarma</h1>
    </div>
    <div class="col-md-7 text-right">
      <div class="btn-group">
        <button type="button" class="btn btn-primary btn-xs">
          <a href="<%= alarms_path %>">Volver al índice de alarmas</a>
        </button>
      </div> 
    </div> 
  </div>
  <hr>
</div>
<div class="row">
  <%= render "form" %>
</div>

app/views/alarms/show.html.erb
<div class="row">
  <%= render partial: "show_header", locals: { alarm: alarm } %>
  
  <div class="alarm-info col-md-12 well">
    <div id="no-receivers-main-message" class="col-md-12 advise <%= "hide" if alarm.has_receivers %>">
      <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <strong>Advertencia</strong>
         No has definido ningún destinatario de la alarma, así que no se enviará ninguna notificación cuando se cumpla la condición.<br>
        <a id="add-receiver-link" href="#">Añade el usuario de Twitter o el correo electrónico</a> de aquellas personas que quieres que reciban las notificaciones.
      </div>                
    </div>
    
    <% if @alarm.condition.blank? %>
      <div class="col-md-12 advise">
        <div class="alert alert-danger alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <strong>Advertencia</strong>
           La alarma no tiene condición de cumplimiento. 
           <a id="add-condition-link" href="#">Define la condición</a> que se debe cumplir para que se envíen notificaciones a los destinatarios.
        </div>                
      </div>
    <% end %>
    
    <div id="alarm-tabs" class="col-md-12">
      <ul id="alarm-tab-ul" class="nav nav-tabs">
        <li class="active"><a id="tab-notifications-link" href="#thrown" data-toggle="tab">Notificaciones de alarma (<%= alarm.notifications_count %>)</a></li>
        <li><a href="#condition" data-toggle="tab">Condición de la alarma</a></li>
        <li><a id="tab-samples-link" href="#sample" data-toggle="tab"><%= alarm.tab_samples_title %></a></li>
        <li><a id="tab-receivers-link" href="#receivers" data-toggle="tab"><%= alarm.tab_receivers_title %></a></li>
      </ul>
      
      <div class="tab-content">
        <div class="tab-pane active" id="thrown">
          <%= render partial: "notifications/tab_notifications", locals: { alarm: alarm, notifications: @notifications, page: @notifications_page } %>
        </div>
        <div class="tab-pane" id="condition">
          <%= render partial: "operations/tab_operations", locals: { alarm: @alarm, operators: @operators, operator_types: @operator_types } %>
        </div>
        <div class="tab-pane" id="sample">
          <%= render partial: "samples/tab_samples", locals: { alarm: alarm, samples: @samples, page: @samples_page } %>
        </div>
        <div class="tab-pane" id="receivers">
          <%= render partial: "receivers/tab_receivers", locals: { alarm: alarm, receivers: @receivers, page: @receivers_page } %>
        </div>
      </div>
    </div>
  </div>
</div>


<% content_for :script do %>
  <%= javascript_include_tag "alarms/show" %>
<% end %>

app/views/alarms/update.js.erb
$.pnotify({
  text: '<%= @message.html_safe %>',
  type: '<%= @status == :ok ? "success" : "error" %>'
});

<% if @status == :ok %> 
  $("#alarm-info-container").html('<%= escape_javascript(render(partial: "alarm_info", locals: { alarm: AlarmDecorator.decorate(@alarm) }).html_safe) %>');
  $("#edit-alarm-placeholder").html('').addClass("hide");
  $(".alarm-info").removeClass("hide");
<% else %>
  <% if !has_error_class(@alarm.errors, :name).blank? %>
    $("#form-group-name").addClass("has-error");
    $("#form-group-name").append('<%= escape_javascript(render(partial: "shared/control_error_text", locals: { errors: @alarm.errors, symbol: :name }).html_safe) %>');
  <% end %>
  <% if !has_error_class(@alarm.errors, :description).blank? %>
    $("#form-group-description").addClass("has-error");
    $("#form-group-description").append('<%= escape_javascript(render(partial: "shared/control_error_text", locals: { errors: @alarm.errors, symbol: :description }).html_safe) %>');
  <% end %>
<% end %>