config/routes.rb
Mathalarm::Application.routes.draw do
  
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :alarms, only: [:index, :show] do
        resources :samples, except: [:new, :edit]
      end
    end
  end

  resources :home, only: [:index]
  resources :plans, only: [:index]
  
  match "/alarms/:id/export(/:notification_id)", as: "export_alarm", to: "alarms#export", via: [:get] 
  
  resources :alarms do
    resources :samples, except: [:show]
    resources :receivers, except: [:show]
    resources :notifications, only: [:index, :show]
    resources :imports, only: [:new, :create]    
  end
  
  root :to => 'home#index'

end

app/views/layouts/_logged_navbar.html.erb
<div class="navbar navbar-default navbar-fixed-top ma-navbar" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand ma-navbar-text" href="<%= alarms_path %>">MathAlarm.com</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#" class="ma-navbar-text">Ayuda</a></li>
        <li><a href="#" class="ma-navbar-text">Mi cuenta</a></li>
        <li><a href="/users/sign_out" class="ma-navbar-text">Salir</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_unlogged_navbar.html.erb
<%= javascript_include_tag "home" %>  

<div class="navbar navbar-default navbar-fixed-top ma-navbar" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand ma-navbar-text" href="<%= root_path %>">MathAlarm.com</a>
    </div>
    <div class="navbar-collapse collapse">      
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#" class="ma-navbar-text">¿Qué es?</a></li>
        <li><a href="<%= plans_path %>" class="ma-navbar-text">Precios</a></li>
        <li class="space">&nbsp;</li>
        <li><button class="btn btn-sm btn-primary login">Acceder</button></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>MathAlarm</title>
    <%= include_gon %>
    <%= favicon_link_tag %>
    
    <%= javascript_include_tag "application" %>    
    <%= stylesheet_link_tag    "application", "bootstrap.min", "jquery.pnotify.default", "jquery.pnotify.default.icons", "pace" %>


    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="container">
      <%= render user_signed_in? ? "layouts/logged_navbar" : "layouts/unlogged_navbar" %>	
	  
      <%= yield %>
      
      <div class="row">
        <hr>
        <footer>
          <p>MathAlarm.com &copy; 2014</p>
        </footer>
      </div>
    </div>
    
    <%= yield :script %>      

  </body>
</html>